version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    redis:
        image: redis
        ports:
        - "6379:6379"
    php:
        build: .
        image: php:fpm
        volumes:
            - ./code:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
