version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    redis:
        image: redis
        ports:
        - "6379:6379"
    elasticsearch:
        image: elasticsearch:latest
        container_name: elasticsearch
        ports:
        - "9200:9200"
        - "9300:9300"
    mysql:
        image: mysql
        ports:
        - "33061:3306"
        - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 280384483082
    php:
        build: .
        image: php:fpm
        volumes:
            - ./code:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
